// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://gohcnlyonuoeszaqjsxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvaGNubHlvbnVvZXN6YXFqc3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxNDcwOTcsImV4cCI6MjA4NTcyMzA5N30.c_orJdf-aGfIThYRGvfgEMRkVvTPpajdrCBNJPRbzlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
