// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

/**
 * Prefer environment variables so this app can point to the *correct* Supabase project.
 *
 * In Vite, env vars must be prefixed with `VITE_`.
 */
const ENV_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const ENV_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

// Backward-compatible defaults (previous hardcoded project).
const FALLBACK_URL = "https://gohcnlyonuoeszaqjsxw.supabase.co";
const FALLBACK_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvaGNubHlvbnVvZXN6YXFqc3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxNDcwOTcsImV4cCI6MjA4NTcyMzA5N30.c_orJdf-aGfIThYRGvfgEMRkVvTPpajdrCBNJPRbzlY";

const SUPABASE_URL = (ENV_URL && ENV_URL.trim()) || FALLBACK_URL;
const SUPABASE_ANON_KEY = (ENV_ANON_KEY && ENV_ANON_KEY.trim()) || FALLBACK_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Optional exports for debugging/observability.
export const supabaseUrl = SUPABASE_URL;